const actionTypes = {
  LOADING_CARDS: "LOADING_CARDS",
  SUCCESS_GETTING_CARDS: "SUCCESS_GETTING_CARDS",
  FAILED_GETTING_CARDS: "FAILED_GETTING_CARDS",
  SET_CURRENT_CARD: "SET_CURRENT_CARD",
  SET_CURRENT_THEME: "SET_CURRENT_THEME"
};
export default actionTypes;
